#!/usr/bin/env bash

#SBATCH -J sette
#SBATCH -o sette.%j.out
#SBATCH -e sette.%j.err
#SBATCH --parsable
#SBATCH -N 1
#SBATCH --time=0-00:30:00
#SBATCH --account=frtomerc
#SBATCH --partition=gpil
#SBATCH --qos=nf
#SBATCH --mem=64GB
#SBATCH --ntasks=TOTAL_NPROCS

set +x

# Test specific settings. Do not hand edit these lines; the fcm_job.sh script will set these
# (via sed operating on this template job file). 
#
  echo " ";
  OCORES=NPROCS
  XCORES=NXIOPROCS
  TCORES=$((OCORES+XCORES))
#
###############################################################
###############################################################
#
# Don't remove neither change the following line
# BODY
#
# Test specific settings. Do not hand edit these lines; the fcm_job.sh script will set these
# (via sed operating on this template job file). Note that the number of compute nodes required
# is also set by the fcm_job.sh on the PBS select header line above.
#
# These variables are needed by post_test_tidyup function in all_functions.sh
#
  export SETTE_DIR="DEF_SETTE_DIR"
  export MPIRUN="srun"
  export NEMO_VALIDATION_DIR="DEF_NEMO_VALIDATION"
  export NEW_CONF="DEF_NEW_CONF"
  export CMP_NAM="DEF_CMP_NAM"
  export TEST_NAME="DEF_TEST_NAME"
  export EXE_DIR="DEF_EXE_DIR"
#
# load sette functions (only post_test_tidyup needed)
  . ${SETTE_DIR}/all_functions.sh
#
# Load environment if exists
  env_file=`find ${SETTE_DIR}/../arch -name arch-${CMP_NAM}.env`
  if [ -f "${env_file}" ] ; then
     echo "Load environment file arch-${CMP_NAM}.env"
     . ${env_file}
  fi

  ulimit -s unlimited
  ulimit -a
#
# end of set up
###############################################################
#
# change to the working directory 
#
  cd ${EXE_DIR}
  echo Running on host `hostname`
  echo Time is `date`
  echo Directory is `pwd`
# 
#  Run the parallel MPI executable 
#
  echo "Running time ${MPIRUN} ./nemo"
#
# ICE_AGRIF bug with XIOS
  if [[ ${NEW_CONF} =~ "ICE_AGRIF" ]]; then
    sed -i'' -e 's/detect_missing_value="true"/detect_missing_value="false"/' field_def_nemo-ice.xml
  fi
#
  if [ $XCORES -gt 0 ]; then
#
#  Run MPMD case
#
     # XIOS
     if [ $XCORES -gt 0 ] && [ -f ${XIOS_DIR:-${XIOS_prefix}}/bin/xios_server.exe ]; then
        cp -a ${XIOS_DIR:-${XIOS_prefix}}/bin/xios_server.exe .
        [[ ! ${NEW_CONF} =~ "_OBS" ]] && sed -i "s/one_file/multiple_file/" file_def_nemo-*.xml
     fi

     # CONFIG FILE
     cat > ./config.file <<-EOF
0-$((OCORES-1)) ./nemo
${OCORES}-$((TCORES-1)) ./xios_server.exe
EOF  

     $MPIRUN --ntasks=$TCORES --multi-prog config.file

  else
#
# Run SPMD case
#
    $MPIRUN --ntasks=$TCORES ./nemo
  fi
#

#
(post_test_tidyup) || exit $?

# END_BODY
# Don't remove neither change the previous line