# ======================================================================
#                    ***  sette/sette_record.py  ***
# NEMO SETTE-validation-database records
# ======================================================================
# History : 5.1  !  2026-06  (S. Mueller) Initial version
# ----------------------------------------------------------------------
#
# ----------------------------------------------------------------------
# NEMO/SETTE 5.1.a, NEMO Consortium (2026)
# Software governed by the CeCILL license (see ./LICENSE)
# ----------------------------------------------------------------------
#
"""NEMO SETTE-validation-database records

The SETTE validation database is a hierarchical four-tier directory
structure that holds records generated by SETTE test runs (test-run
output files) in its lowest-ranked directories. It is located inside an
existing directory (located at path <base>) and individual files
are locatable through five identifiers (<revision>, <variant>,
<configuration>, <test run>, and <file>) at the file path
    <base>/<revision>/<variant>/<configuration>/<test run>/<file>.
This module provides a class to facilitate the access to such records.
"""

import pathlib
from sette.sette_identifier import SetteIdentifierRevision
from sette.sette_identifier import SetteIdentifierVariant
from sette.sette_identifier import SetteIdentifierConfiguration
from sette.sette_identifier import SetteIdentifierTestrun
from sette.sette_identifier import SetteIdentifierFile
from sette.sette_error import SetteErrorIdentifier, SetteErrorPath

class SetteRecord():
    """Handles the path to individual SETTE records

    Instances of this class can be set to point to individual files or
    to identifier groups of the four-tier hierarchical database: all but
    the lowest-ranked identifier of a specified (sub)path have to exist,
    with non-existent identifiers indicating new entries or
    subdirectories; undefined identifiers can be interpreted as wild
    cards; unconnected identifiers are ignored.
    """

    # Base path of the database
    _base = None
    # Depth of the current record path
    _depth = 0
    # Identifiers
    _identifiers = [None, None, None, None, None]
    # Flag existence of current set of identifiers
    exists = True

    def __init__(self, base, revision=None, variant=None, configuration=None,
            testrun=None, file=None):
        """Initialise the base path and, optionally, identifiers"""
        # Validate and set base path
        self.base = base
        # Initialise identifiers
        self._identifiers = [SetteIdentifierRevision(),
                SetteIdentifierVariant(), SetteIdentifierConfiguration(),
                SetteIdentifierTestrun(), SetteIdentifierFile()]
        if revision is not None:
            self.revision = revision
        if variant is not None:
            self.variant = variant
        if configuration is not None:
            self.configuration = configuration
        if testrun is not None:
            self.testrun = testrun
        if file is not None:
            self.file = file

    @property
    def base(self):
        """Base path of the SETTE validation database"""
        return self._base

    @base.setter
    def base(self, path):
        """Base path of the SETTE validation database"""
        if isinstance(path, pathlib.Path):
            self._base = path.resolve()
        elif isinstance(path, str):
            self._base = pathlib.Path(path).resolve()
        else:
            raise SetteErrorPath('unknown base-path type')
        # Check if the base path is suitable to contain a SETTE
        # validation database (i.e., if it is an existing directory)
        if not self._base.is_dir():
            raise SetteErrorPath('non-existent SETTE validation database '+
                    'selected')
        # Re-set (i.e., re-validate) defined identifiers and depth after
        # change of the database base path
        for depth in range(len(self._identifiers)):
            if self._identifiers[depth] is not None:
                if self._identifiers[depth].value is not None:
                    self._set_identifier(depth, self._identifiers[depth].value)

    @property
    def depth(self):
        """Depth of the current record path"""
        return self._depth

    @depth.setter
    def depth(self, depth):
        """Depth of the current record path"""
        self._depth = max(0, min(5, depth))

    @property
    def depth_type(self):
        """Type associated with the identifier at the current depth"""
        if self._identifiers[self.depth] is not None:
            return self._identifiers[self.depth].identifier_type

    def _get_identifier(self, depth):
        """Return the specified identifier"""
        return self._identifiers[depth].value

    def _set_identifier(self, depth, value):
        """Set the specified identifier"""
        # Set the identifier only if the upstream identifier is defined
        if depth > 0:
            if (self._identifiers[depth-1] is None or
                    self._identifiers[depth-1].value is None):
                raise SetteErrorIdentifier('unconnected identifier, ignored',
                        self._identifiers[depth].identifier_type)
                return
            else:
                path = self._identifiers[depth-1].path
                path /= self._identifiers[depth-1].value
        else:
            path = self.base
        # Set or delete the identifier, and update the associated path
        # and lookup data
        if value is not None:
            self._identifiers[depth].value = value
            self._identifiers[depth].path = path
            self.depth = max(depth+1, self.depth)
        # Update the path or truncate the downstream path
        truncate = False
        for n in range(depth, self.depth):
            if not truncate and value is None:
                truncate = True
                self.depth = n
            if truncate:
                del self._identifiers[n].value
            else:
                self._identifiers[n].path = path
                self.exists = self._identifiers[n].exists
                self.depth = n+1
                if not self.exists:
                    truncate = True
                path /= self._identifiers[n].value

    @property
    def revision(self):
        """SETTE revision identifier"""
        return self._get_identifier(0)

    @revision.setter
    def revision(self, value):
        """SETTE revision identifier"""
        self._set_identifier(0, value)

    @property
    def variant(self):
        """SETTE variant identifier"""
        return self._get_identifier(1)

    @variant.setter
    def variant(self, value):
        """SETTE variant identifier"""
        self._set_identifier(1, value)

    @property
    def variant_lookup(self):
        """SETTE variant lookup data"""
        return self._identifiers[1].lookup

    @property
    def configuration(self):
        """SETTE configuration identifier"""
        return self._get_identifier(2)

    @configuration.setter
    def configuration(self, value):
        """SETTE configuration identifier"""
        self._set_identifier(2, value)

    @property
    def testrun(self):
        """SETTE test-run identifier"""
        return self._get_identifier(3)

    @testrun.setter
    def testrun(self, value):
        """SETTE test-run identifier"""
        self._set_identifier(3, value)

    @property
    def file(self):
        """SETTE file identifier"""
        return self._get_identifier(4)

    @file.setter
    def file(self, value):
        """SETTE file identifier"""
        self._set_identifier(4, value)

    def __str__(self):
        """Display the record path"""
        return '/'.join([i.value for i in self._identifiers[:self.depth]])

    def list(self, depth=99):
        """List existing identifiers just below the specified depth"""
        depth = max(0, min(self.depth, depth))
        names = []
        test = self.copy(depth=depth)
        if depth > 0:
            path = test._identifiers[test.depth-1].path.joinpath(
                    test._identifiers[test.depth-1].value)
        else:
            path = test.base
        if path.is_dir():
            for p in path.iterdir():
                try:
                    test._set_identifier(test.depth, p.name)
                    if test.exists:
                        names.append(p.name)
                except:
                    pass
                else:
                    test._set_identifier(test.depth-1,None)
        return names

    def focus(self, identifier):
        """Append an existing identifier to the path"""
        valid = self.list()
        if isinstance(identifier, str) and identifier in valid:
            self._set_identifier(self.depth, identifier)
        elif isinstance(identifier, int) and identifier in range(len(valid)):
            self._set_identifier(self.depth, valid[identifier])
        elif self.depth > len(self._identifiers):
            raise SetteErrorPath('path cannot be extended')
        else:
            raise SetteErrorIdentifier('identifier does not exist, ignored',
                    self._identifiers[self.depth].identifier_type)

    def blur(self):
        """Remove the lowest-ranked identifier from the current path"""
        if self.depth > 0:
            self._set_identifier(self.depth-1, None)
        else:
            raise SetteErrorPath('path at database root, shortening attempt '+
                    'ignored')

    def reset(self):
        """Remove all identifiers"""
        self._set_identifier(0, None)

    def copy(self, depth=99):
        """Copy (full or partial) the current record path"""
        depth = max(0, min(self.depth, depth))
        new = SetteRecord(base=self.base)
        for n in range(max(0, min(depth, self.depth))):
            new._set_identifier(n, self._get_identifier(n))
        return new
